apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironman-activate-suit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ironman-activate-suit
  template:
    metadata:
      labels:
        app: ironman-activate-suit
    spec:
      containers:
        - name: ironman-activate-suit
          image: ironman-orchestrator:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ironman-activate-suit
spec:
  selector:
    app: ironman-activate-suit
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
