apiVersion: apps/v1
kind: Deployment
metadata:
  name: armor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: armor-service
  template:
    metadata:
      labels:
        app: armor-service
    spec:
      containers:
        - name: armor-service
          image: armor-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: armor-service
spec:
  selector:
    app: armor-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
