apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: ai-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
