apiVersion: apps/v1
kind: Deployment
metadata:
  name: weapon-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weapon-service
  template:
    metadata:
      labels:
        app: weapon-service
    spec:
      containers:
        - name: weapon-service
          image: weapon-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
---
apiVersion: v1
kind: Service
metadata:
  name: weapon-service
spec:
  selector:
    app: weapon-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006
